<?php

namespace AppBundle\Repository;

/**
 * CapitalInvestmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CapitalInvestmentRepository extends \Doctrine\ORM\EntityRepository
{
}
