<?php

namespace AppBundle\Repository;

/**
 * CocineroRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CocineroRepository extends \Doctrine\ORM\EntityRepository
{
}
