<?php

namespace AppBundle\Repository;

/**
 * InvesmentExpenditureRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InvesmentExpenditureRepository extends \Doctrine\ORM\EntityRepository
{
}
