<?php

namespace AppBundle\Repository;

/**
 * PlateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlateRepository extends \Doctrine\ORM\EntityRepository
{
}
