<?php

namespace AppBundle\Repository;

/**
 * PlateSetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlateSetRepository extends \Doctrine\ORM\EntityRepository
{
}
