<?php

namespace AppBundle\Repository;

/**
 * VendedorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VendedorRepository extends \Doctrine\ORM\EntityRepository
{
}
