# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false


    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    AppBundle\:
        resource: '../../src/AppBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/AppBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        public: true
        tags: ['controller.service_arguments']
      # ...
    admin.capital_investment:
        class: AppBundle\Admin\CapitalInvestmentAdmin
        arguments: [~, AppBundle\Entity\CapitalInvestment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Capital Investment }
        public: true
    admin.common_expenses:
        class: AppBundle\Admin\CommonExpensesAdmin
        arguments: [~, AppBundle\Entity\CommonExpenses, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Common Expenses }
        public: true
    admin.invesment_expenditure:
        class: AppBundle\Admin\InvesmentExpenditureAdmin
        arguments: [~, AppBundle\Entity\InvesmentExpenditure, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Invesment Expenditure }
        public: true
    admin.PaymentAdmin:
        class: AppBundle\Admin\PaymentAdmin
        arguments: [~, AppBundle\Entity\Payment, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Payment }
        public: true
    admin.SaleAdmin:
        class: AppBundle\Admin\SaleAdmin
        arguments: [~, AppBundle\Entity\Sale, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Sale }
        public: true
    admin.PersonAdmin:
        class: AppBundle\Admin\PersonAdmin
        arguments: [~, AppBundle\Entity\Person, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Person }
        public: true
    admin.RoleAdmin:
        class: AppBundle\Admin\RoleAdmin
        arguments: [~, AppBundle\Entity\Role, ~]
        tags:
            - { name: sonata.admin, manager_type: orm, label: Role }
        public: true

    # add more services, or override services that need manual wiring
    # AppBundle\Service\ExampleService:
    #     arguments:
    #         $someArgument: 'some_value'
